trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azureSubscription'
  acrConnection: 'acrConnection' 
  acrLoginServer: 'acrincludia2771.azurecr.io'
  webAppName: 'app-includia-iot-2771'
  dockerfilePath: 'includia/includia-iot/IncludIA-IOT-b5f91d4febb88ce88f0174cb6cc02c8827528275/Dockerfile'
  buildContext: 'includia/includia-iot/IncludIA-IOT-b5f91d4febb88ce88f0174cb6cc02c8827528275'
  
steps:
- task: Docker@2
  displayName: 'Build & Push IoT'
  inputs:
    containerRegistry: '$(acrConnection)'
    repository: '$(webAppName)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    tags: 'latest'

- task: AzureWebAppContainer@1
  displayName: 'Deploy IoT to Azure'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(webAppName)'
    containers: '$(acrLoginServer)/$(webAppName):latest'
    appSettings: '-GOOGLE_API_KEY "$(GOOGLE_API_KEY)"'